### PR TITLE
Moved filtering and sorting logic to the client side, closes #2

### LINKED ISSUE #2: Fix pagination on 'View Profiles'
When a user filters down the results in anyway the pagination needs to reflect the new total number of listings. Currently, if there are 15 records available and they filter down to 5 then the pagination SHOULD show page 1 only, not 1 through 3.

### PR DESCRIPTION
**Pull request by jonahgeorge**
Moved filtering and sorting logic to the client side.

`Api::UserController#index` has been modified to no longer do limiting,
sorting, or ordering. Additionally the `meta.count` attribute now returns
the length of the rendered json array (meaning it could be removed later).

On the React side, UserBox and UserList have been modified to account for
these changes _and_ UserPagination has been removed. The inital server response
is cached in the `this.state.data` attribute and all subsequent operations use
`this.state.users` to manipulate the "working set".

Todo:
- [ ] Handle button click on table header in a nice manner
- [x] Fix N+1 query in `Api::UserController#index` (re: `route_count`)
- [x] Downcase form field input and user data when filtering (to prevent case mismatches)

### CODE REVIEW

**Comment by jonahgeorge** [comment]
Still need to figure out a nice way of handle button click on the table header. Currently it is too easy to select the text.

**Comment by jonahgeorge** [comment]
Also, there seems to be an n+1 query in the `#index` action regarding the `route_count`.

**Comment by jonahgeorge** [comment]
9c8847cc-be9a-11e4-8244-df70d285068a

**Comment by skeltont** [comment]
YESSSSS :+1:

**Comment by skeltont** [comment]
Is this ready for me to pull? I was gonna ask about it, but I forgot.

**Comment by jonahgeorge** [comment]
Hmmm... I don't remember. I'll take a look at it tonight

**Comment by jonahgeorge** [comment]
Alright. Pretty sure its ready

**Pull request merged**
