### PR TITLE
adds field to routes for descriptions

### PR DESCRIPTION
**Pull request by skeltont**

### CODE REVIEW

**Comment by jonahgeorge** [comment]
Thoughts on putting a "Description" label in the show page? 
Or we could do a panel with "Description" title and put the body below?
The way it is now is a little ambiguous about what the text actually means.

screen shot 2016-04-06 at 11 36 14 am

**Comment by skeltont** [comment]
I'll see how that looks now

**Comment by skeltont** [comment]
trying to make it not look like this:
screen shot 2016-04-06 at 11 41 18 am
I'd like the label to sit above in the table

**Comment by skeltont** [comment]
I'm honestly okay with it not having a 'Description' label at all:
screen shot 2016-04-06 at 11 45 39 am

**Comment by jonahgeorge** [comment]
Yea, for the longer descriptions it looks much better. 
Maybe this is something we could revisit during the design polish.

**Comment by jonahgeorge** [comment]
I'll merge and deploy

**Pull request merged**
