### PR TITLE
adds the ability to add routes to the database.

### LINKED ISSUE #32: Develop 'Add Route' functionality
we need to be able to track routes 
- [x] link in navbar
- [x] new.html.erb template
- [x] controller logic for creating a new route
- [x] basic authorization protection

### PR DESCRIPTION
**Pull request by skeltont**
Closes #32. Haven't looked at this code in awhile, I could be missing some things. Overall it's functional though.

### CODE REVIEW

**Comment by jonahgeorge** [comment]
:dancers:

**Comment by skeltont** [comment]
:sake:

**Comment by jonahgeorge** [comment]
Let's move [grades](https://github.com/temporary-name/ICCapi/blob/add_create_route/app/controllers/routes_controller.rb#L25-L38) and [locations](https://github.com/temporary-name/ICCapi/blob/add_create_route/app/controllers/routes_controller.rb#L21-L24) into [`ActiveRecord::Enum`](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) on the model.

Should also fix our sorting issues with grades on the index pages.

**Comment by jonahgeorge** [comment]
Let's move the [`rescue_from`](https://github.com/temporary-name/ICCapi/blob/add_create_route/app/controllers/routes_controller.rb#L4) in the RoutesController to ApplicationController following [this](https://github.com/elabs/pundit#rescuing-a-denied-authorization-in-rails) pattern.

**Pull request merged**
